### ISSUE TITLE
Support blur content inside only

### ISSUE THREAD

**Issue by jiangnan44** [skydoves/Cloudy#13]
I need  to blur an Image as background of a  ConstraintLayout , but Cloudy seems to blur everything overlay .
Please consider add this feture

**Comment by nubpro** [comment]
Love to see this happen too!
@skydoves Please grant us the wish, you'll make a lot us very happy :)

**Comment by nubpro** [comment]
```
Box {
  Cloudy() {
      Box(
          modifier = Modifier
              .fillMaxSize()
              .background(Color(255, 255, 255).copy(alpha = 0.38f))
      )
  }
  Text(
      text = stringResource("Text here"),
      color = Color.Black,
      fontSize = 60.sp
  )
}
```

![image](https://github.com/skydoves/Cloudy/assets/762914/716aaf4c-0c87-4e5a-9851-c3273d200488)


Im trying to blur the background only but it seems to be applying the blur around the text on top of it.

**Comment by pavelperc** [comment]
Also, when scrolling, scroll content is usually shifted. This makes the library useless.
<img width="200" alt="image" src="https://github.com/skydoves/Cloudy/assets/31820550/6c15a302-a4f2-4ba2-80d6-616db4d01bff">

**Comment by vrajendraBhavsar** [comment]
Hey @skydoves, 
Could you please provide a better way to handle this issue? I'm thinking of adding this to my project but it seem a bit unstable at this point, thanks a bunch in advance!

**Comment by skydoves** [comment]
Hey guys, the new version 0.2.0 has been released, and now you can resolve this issue by using the `Modifier.cloudy` modifier instead of the `Cloudy` composable function.

**Comment by nubpro** [comment]
> Hey guys, the new version 0.2.0 has been released, and now you can resolve this issue by using the `Modifier.cloudy` modifier instead of the `Cloudy` composable function.

Havent tried it but thank you!
