### ISSUE TITLE
Continuously recalculate blur

### ISSUE THREAD

**Issue by Myzel394** [skydoves/Cloudy#15]
**Is your feature request related to a problem?**

When you have a non-state related change (for example a live preview of the camera), the image seems to be frozen.

**Describe the solution you'd like:**

Add an option to continuously recalculate the blur. Maybe add a parameter `recalculationInterval` that can be a number and will force an update every ms. 0 would mean "off" in this case. `recalculationInterval = 16` for example would mean an update every 16ms.

**Describe alternatives you've considered:**

As a workaround I was thinking of adding a state that updates itself in intervals and thus forces recalculation.

**Comment by skydoves** [comment]
Hey @Myzel394, in the new release 0.2.0, the blurring logic has been changed under the hood, so I'm closing this issue. If you still face the similar issue with the 0.2.0, please reopen this one. Thanks!
