### ISSUE TITLE
2 files found with path 'lib/arm64-v8a/librenderscript-toolkit.so' from inputs:

### ISSUE THREAD

**Issue by akardas16** [skydoves/Cloudy#24]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

When I add dependency, build failed with error below
```
2 files found with path 'lib/arm64-v8a/librenderscript-toolkit.so' from inputs:
 - C:\Users\Abdullah\.gradle\caches\transforms-3\23515a2d5ac95b51b5e088c48f2c0985\transformed\landscapist-transformation-2.3.2\jni\arm64-v8a\librenderscript-toolkit.so
 - C:\Users\Abdullah\.gradle\caches\transforms-3\ff9c9829dce8f7dd285ca53b4fe40b06\transformed\cloudy-0.1.2\jni\arm64-v8a\librenderscript-toolkit.so
If you are using jniLibs and CMake IMPORTED targets, see
https://developer.android.com/r/tools/jniLibs-vs-imported-targets


```

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hi @akardas16, sorry for the late response, You can resolve this issue by adding this to the module that uses Cloudy or your app module.

```gradle
packagingOptions {
    pickFirsts.add("lib/*/librenderscript-toolkit.so")
}
```

**Comment by akardas16** [comment]
> Hi @akardas16, sorry for the late response, You can resolve this issue by adding this to the module that uses Cloudy or your app module.
> 
> ```groovy-gradle
> packagingOptions {
>     pickFirsts.add("lib/*/librenderscript-toolkit.so")
> }
> ```

Still not working. I have got same error after adding it
