### ISSUE TITLE
When used for LazyList items app got crashed with - Failed to copy pixels of the given bitmap!

### ISSUE THREAD

**Issue by KothamireNarendra** [skydoves/Cloudy#3]
When used for LazyList items app got crashed with - Failed to copy pixels of the given bitmap!
Inside sample app you blurred the whole grid instead what I want is to blur individual list item (Basically Image loaded with Coil), How can we do that can you share the sample

**Comment by orlandev** [comment]
You can use this [BlurHash](https://blurha.sh/) and this [component](https://github.com/orlandev/compose-image-blurhash) to perform that using coil.

**Comment by KothamireNarendra** [comment]
@orlandev Wow thanks for help looking awesome

**Comment by skydoves** [comment]
Hi @KothamireNarendra, check out the [Blur Effects Depending on States](https://github.com/skydoves/Cloudy#blur-effects-depending-on-states) and you can see the sample codes on this project.

You can consider using the [Landscapist-Transformation](https://github.com/skydoves/landscapist#transformation) plugin to use the blur effect for your remote images.

**Comment by skydoves** [comment]
I am closing this issue for now.
