### ISSUE TITLE
Crash on API 28 But working on API 31

### ISSUE THREAD

**Issue by Chandra-Sekhar-Bala** [skydoves/Cloudy#35]
**Please complete the following information:**
- Library Version [v 0.2.0]
- Affected Device(s) [Pixel 8 API 28]
 
**Describe the Bug:**

While the Blur Working fine on Pixel 7a API 31 but when the same app runs on Pixel 8 API 28 it crashes. Attaching [the Log](https://gist.github.com/Chandra-Sekhar-Bala/b51bb4e1e53fe3adc4b6b023dd3d0a51) for reference.

**Expected Behavior:**
Should work on all devices.

**Comment by skydoves** [comment]
Hey @Chandra-Sekhar-Bala, it's a known issue by the Jetpack Compose UI. Would you try again with the new release `0.2.1`?

**Comment by Chandra-Sekhar-Bala** [comment]
Hi @skydoves,
I tried updating to new version i.e ```0.2.1```. Sync successfully, but I keep getting this error when I tried to build the project. : 
```
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform kotlin-stdlib-2.0.10.jar (org.jetbrains.kotlin:kotlin-stdlib:2.0.10) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.jvm.environment=standard-jvm, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for EnumerateClassesTransform: C:\Users\pc\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\2.0.10\9120f9dd349d5c67fa6710c4049c3128ef6b51db\kotlin-stdlib-2.0.10.jar.
         > zip END header not found
```

**Comment by skydoves** [comment]
Hey @Chandra-Sekhar-Bala, would you update your kotlin version to 2.0.10?

**Comment by Chandra-Sekhar-Bala** [comment]
Update: Updating library version from ```"0.2.0"``` to ```"0.2.3"``` solved backward compatibility issue.
Thanks @skydoves 🙌
p.s: Kotlin version used: ```"2.0.0"```
