### ISSUE TITLE
Children not visible inside dialog

### ISSUE THREAD

**Issue by BrianMwas** [skydoves/Cloudy#9]
**Please complete the following information:**
- v0.1.2
- Oppo A23 v11
 
**Describe the Bug:**

Using Cloudy in a Display composable Dows not allow other components to be drawn. It works well but anything inside it does not show

**Expected Behavior:**

When I use Cloudy within a Dialog it should allow me to see the children nested inside a container or layout

**Comment by vickyleu** [comment]
same

**Comment by skydoves** [comment]
Hey guys, the new version 0.2.0 has been released, and now you can resolve this issue by using the `Modifier.cloudy` modifier instead of the `Cloudy` composable function.
